### ISSUE TITLE
Effect of Ghost_bridge rules on avatar and web interface

### ISSUE THREAD

**Issue by EskenderTamrat** [opencog/ghost_bridge#12]
In the HR stack, I couldn't see the effect of the avatar playing the emotions I run with ghost_bridge and there is no related output on the webui.

The following is a sample rule and its response in bash.

`(ghost-parse "u: (hello) ^gesture(lookLR, 0.24, 1.23, 1)")`

`(test-ghost "hello world")`  

`[2018-08-06 13:21:23:296] [INFO] [gesture] (lookLR 0.24 1.23 1)
[2018-08-06 13:21:23:297] [INFO] [say] (hello there)
$2 = ((WordNode "hello")
 (WordNode "there")
 (Node "finished-action")
)
`

**Comment by AmeBel** [comment]
After compiling atomspace and opencog against python 2.7 (see [here](https://github.com/AmeBel/atomspace/blob/471292af518333564d41ee9c1d90be656dc43a34/CMakeLists.txt) for changes). Running the following rule will get the avator mouth to move, so it could be the values passed to the `gesture` function or some other bug.
```scheme
(ghost-parse "u: (hello) world world la la la la ^gesture(lookLR, 0.24, 1.23, 1) ^keep")
(ghost "hello")
```

**Comment by simonmekit** [comment]
Running (ghost-run) command in cogserver-shell before writing a rule will create a thread (something like this: #<thread 140057868494592 (11e3380)> ) that handles the communication b/n ghost and the avatar.

Its working now in my machine. So the issue should be, even though ghost_bridge is running, ghost was not really started until (ghost-run) command issued.
https://github.com/singnet/opencog/tree/master/opencog/ghost#how-to-run

**Comment by AmeBel** [comment]
@simonmekit that is partially correct
- `(ghost-run)` isn't handling communication between ghost and the avator. 
- `(ghost-run)` is called [at line 74 of load-opencog.scm](https://github.com/opencog/ghost_bridge/blob/3fa6aed3095cabe70a7d9c3e647cf528c3140d1b/scripts/load-opencog.scm#L74) but before that, if the atomspace is compiled against python3,  it would fail [at line 20](https://github.com/opencog/ghost_bridge/blob/3fa6aed3095cabe70a7d9c3e647cf528c3140d1b/scripts/load-opencog.scm#L20).
